# Generated by Django 4.2.10 on 2024-02-10 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=12)),
                ('mname', models.CharField(max_length=12)),
                ('lname', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=100)),
                ('dp', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=90)),
                ('state', models.CharField(max_length=90)),
                ('country', models.CharField(max_length=90)),
                ('terms', models.CharField(max_length=1)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=122)),
                ('title', models.CharField(max_length=195)),
                ('publish', models.IntegerField(blank=True, null=True)),
                ('views', models.IntegerField(blank=True, default='0', null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tlog_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=122, null=True)),
                ('date', models.DateTimeField()),
                ('tlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tlogs')),
            ],
        ),
        migrations.CreateModel(
            name='Tlog_body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=122, null=True)),
                ('title', models.CharField(blank=True, max_length=195, null=True)),
                ('date', models.DateField()),
                ('tlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tlogs')),
            ],
        ),
    ]
