# Generated by Django 4.2.10 on 2024-03-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='verification_key',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='verification_key_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='verified',
            field=models.CharField(blank=True, default='0', null=True),
        ),
    ]
