# Generated by Django 4.2.10 on 2024-03-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_login_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='verified',
            field=models.CharField(blank=True, default=0, null=True),
        ),
    ]
